---

- name: UPDATE-ALTERNATIVE | Vim is my main editor
  alternatives:
    name: editor
    path: "{{ dbs_alternative_editor }}"

- name: UPDATE-ALTERNATIVE | Gawk (GNU awk) is the best
  alternatives:
    name: awk
    path: "{{ dbs_alternative_awk }}"
